### PR TITLE
Gray list for MasterSlave configuration

### PR DESCRIPTION
**Pull request by SeTeM**
Solrb will have two built-in strategies:
- Disabled strategy
- In memory strategy: it stores URLs in an instance variable, so it's not shared across threads/servers. URLs will be marked as "gray" for 5 minutes, but if all URLs are gray, the policy will try to send requests to these URLs earlier.

A redis-based policy can be implemented and used later just like an additional strategy.

### TODO
- [x] Manually test
- [x] Add specs
- [x] Add README

### CODE REVIEW

**Comment by SeTeM** [comment]
I added `Solr::Request::MasterSlave::DefaultNodeSelectionStrategy`, but not sure what solution is better:
1) Add `Solr::Request::MasterSlave::DefaultNodeSelectionStrategy` and filter `Solr.configuration.nodes_gray_list.select_active` inside it (currently I use this way);
2) Change an existing `Solr::Request::DefaultNodeSelectionStrategy` and add a condition to it:
```ruby
module Solr
  module Request
    class DefaultNodeSelectionStrategy < NodeSelectionStrategy
      def call
        urls = Solr.active_nodes_for(collection: collection_name)
        node_urls = map_urls_to_collections(urls).shuffle
        if Solr.master_slave_enabled?
          Solr.configuration.nodes_gray_list.select_active(node_urls)
        else
          node_urls
        end
      end
    end
  end
end
```

**Comment by route** [comment]
That's right I think there won't be any default strategy other than `DefaultNodeSelectionStrategy`. For SOLR standalone it's 1 server, cloud manages nodes itself so we only can order them as we like and only for master-slave we need something like gray-listing. So we might be better with just one `DefaultNodeSelectionStrategy`, but why do we have to change it? It calls `active_nodes_for` which is already defined in given mode where we can query gray-listing hash

**Comment by SeTeM** [comment]
@route, from the technical point of view this solution is worse because there is a confusion between solr url and core/collection url, but otherwise I also though to add gray list filtering to `active_nodes_for`.
Could you review the PR once again?

**Comment by SeTeM** [comment]
I think we should create a top-level class `Solr::Node` and use it across the gem. It should store solr url and a collection name:
```ruby
module Solr
  class Node
    attr_reader :solr_url, :collection_name

    def self.wrap(solr_urls, collection_name:)
      solr_urls.map do |solr_url|
        new(solr_url: solr_url, collection_name: collection_name)
      end
    end
    
    def initialize(solr_url:, collection_name:)
      @solr_url = solr_url
      @collection_name = collection_name.to_s
    end

    def collection_url
      File.join(solr_url, collection_name)
    end
  end
end
```
But that's a topic for the next change.

**Comment by route** [comment]
LGTM

**Pull request merged**
